export const projects = [
  {
    title: 'Project Management',
    description: "Using GraphQL queries and mutations a website to manage projects with client details",
      image: '/images/1.png',
      tags: ['GraphQL','Mongo', 'React'],
    source: 'https://project-mngt.herokuapp.com/',
    visit: 'https://github.com/poojan14/project-management-graphql',
    id: 0,
  },
  {
    title: 'Real Estate',
    description:"NextJS based website to filter and find various Properties for renting or buying",
    image: '/images/2.png',
    tags: ['NextJS','React', 'Rapid API'],
    source: 'https://real-estate-nextjs-eight.vercel.app/',
    visit: 'https://github.com/poojan14/Real-Estate-nextjs',
    id: 1,
  },
  {
    title: 'Chat App',
    description: "Realtime chat application with chatengine.io manage chatrooms and user and sent text or image messages",
      image: '/images/3.png',
      tags: ['React', 'Chat-Engine'],
    source: 'https://chatapp-pvs.netlify.app/',
    visit: 'https://github.com/poojan14/chatapp',
    id: 2,
  },
  {
    title: 'Expense Tracker',
    description: "Keep Track of income and expense and remaining balance with this simple expense tracker",
    image: '/images/4.png',
    tags: ['React', 'Node', 'Mongo'],
    source: 'https://expense-pvs.herokuapp.com/',
    visit: 'https://github.com/poojan14/expense-tracker',
    id: 3,
  },

  {
    title: 'Wordle Game',
    description: "Play this game where you have to guess 5 letter word in maximum 6 tries",
      image: '/images/5.png',
      tags: ['CSS', 'React', 'Node'],
    source: 'https://wordle-game-six.vercel.app/',
    visit: 'https://github.com/poojan14/wordle-game',
    id: 4,
  },
  {
    title: 'Node Packages Blog',
    description:"A blog to keep track of information of many helpful node packages",
    image: '/images/6.png',
    tags: ['EJS','React', 'Mongo'],
    source: 'https://markdown-blog-node-packages.herokuapp.com/',
    visit: 'https://github.com/poojan14/nodejs-blog',
    id: 5,
  },
  {
    title: 'Task Manager - API',
    description: "Manage tasks with this API perform CRUD operations",
      image: '/images/7.png',
      tags: ['Node', 'Swagger-API','Mongo'],
    source: 'https://tasks-pvs.herokuapp.com/',
    visit: 'https://github.com/poojan14/tasks-api',
    id: 6,
  },
  {
    title: 'Quiz Game',
    description: "Test your AngularJS knowledge with this mcq based quiz game",
    image: '/images/8.png',
    tags: ['Javascript', 'CSS', 'HTML'],
    source: 'https://poojan14.github.io/mcq-angularjs/',
    visit: 'https://github.com/poojan14/mcq-angularjs',
    id: 7,
  },

  {
    title: 'Story Book',
    description: "Sign in with google id and create own stories also post as public or private",
      image: '/images/9.png',
      tags: ['Mongo', 'Express', 'GoogleOAuth'],
    source: 'https://storybooks-pvs.herokuapp.com/dashboard',
    visit: 'https://github.com/poojan14/Storybook-nodejs',
    id: 8,
  },
  {
    title: 'Spotify Clone',
    description:"Website to listen my personal favourite songs",
    image: '/images/10.png',
    tags: ['HTML','CSS', 'Javascript'],
    source: 'https://poojan14.github.io/spotify-clone/',
    visit: 'https://github.com/poojan14/spotify-clone',
    id: 9,
  },
  {
    title: 'Avengers Game',
    description: "Play exciting memory based game where you have to pair the Avengers",
      image: '/images/11.png',
      tags: ['Javascript', 'CSS', 'HTML'],
    source: 'https://poojan14.github.io/avengers-card/',
    visit: 'https://github.com/poojan14/avengers-card',
    id: 10,
  },
  {
    title: 'Restaurant Menu',
    description: "View complete menu of restaurant in a single page React with filter and search",
    image: '/images/12.png',
    tags: ['React', 'Node', 'JavaScript'],
    source: 'https://restaurant-menu-react.vercel.app/',
    visit: 'https://github.com/poojan14/restaurant-menu-react',
    id: 11,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'B.Tech from Parul University in CSE', },
  { year: 2021, text: 'M.E from LD College in Software Engineering ', },
  { year: 2022, text: 'Assistant Professor at Saffrony ' ,},
  { year: 'Currently', text: 'Career in Full Stack JS Developer' ,},
];